root: true
env:
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - google
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - tsconfig.json
    - tsconfig.dev.json
  sourceType: module

ignorePatterns:
  - /lib/**/* # Ignore built files

plugins:
  - '@typescript-eslint'
  - import

rules:
  # `var`を使ったら怒るよ
  no-var: error

  # セミコロン抜かないで
  semi: error

  # `==` とかを使わないでね
  eqeqeq: error

  # カンマのあとはスペースを入れてくれ
  comma-spacing: error

  # インデントは2で守ってね
  indent:
    - error
    - 2

  # `console.log`は消しておいて
  no-console: error

  # ブロック演算子はスペース入れてね
  block-spacing: error

    # `{}` の中の前後はスペースを入れてね
  object-curly-spacing: 
    - error
    - always

  # 演算子の前後のスペースは絶対抜かないで
  space-infix-ops: error

  # アロー演算子前後のスペース強制
  arrow-spacing: error

  # タブとスペースを混ぜないで
  no-mixed-spaces-and-tabs: error

  # うるせえ黙れシベリア送りにするぞ
  import/no-unresolved: off

  new-cap: off
